language: cpp
sudo: required
dist: xenial
compiler: g++
os: linux

before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/before_install.sh; fi
install:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/install_dependencies.sh; fi
before_script:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/before_script.sh; fi

script:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/script.sh; fi
after_success:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/success.sh; fi
after_failure:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/failure.sh; fi

before_deploy:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/before_deploy.sh; fi
deploy:
  provider: releases
  api_key:
    secure: System.getenv("_api_key")
  file_glob: true
  file:
    - src/**/*
    - LICENSE
    - README.md
  skip_cleanup: true
  on:
    tags: true
    repo: LamKamhang/MiniCompiler
    branch: master
after_deploy:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/after_deploy.sh; fi
